### ISSUE TITLE
Healthcheck endpoint

### ISSUE THREAD

**Issue by davidkarlsen** [Lotto24/aws-ecr-http-proxy#12]
Hi - could you add a simple endpoint /ping or /health or /healthz/readiness / /healthz/liveness so that the image can run under k8s with health checking?

**Comment by MQasimSarfraz** [comment]
https://github.com/Lotto24/aws-ecr-http-proxy/pull/13

**Comment by davidkarlsen** [comment]
Awesome - that was fast! :)
I've created a [helm-chart](https://helm.sh/docs/topics/charts/) for ecr-proxy, see: 
https://hub.helm.sh/charts/tietoevryfs/ecr-proxy

**Comment by MQasimSarfraz** [comment]
Thanks! :) Charts looks good. 

Please feel free to create a PR to link them in [deployment section](https://github.com/Lotto24/aws-ecr-http-proxy#deploying-the-proxy).
