### ISSUE TITLE
Allow access ECR on base of IAM role

### ISSUE THREAD

**Issue by 1ricardo** [Lotto24/aws-ecr-http-proxy#15]
Hi, 
I using Kubernetes in AWS, but I would like to expose some docker images for people in my office. 
I would like to use your software with IAM Role instead of pass AWSKey and AWSSecret to the Docker. is there any chance to configure without AWSKey.

Currently, Docker doesn't want to start when I don't provide the AWSKey

``` kubectl logs docker-registry-proxy-686c4586fb-4zs7t
+ '[' -z xxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com ]
+ '[' -z 5000 ]
+ '[' -z 8.8.8.8 ]
+ '[' -z eu-west-1 ]
+ '[' -z  ]
+ '[' -z  ]
+ echo 'AWS_ACCESS_KEY_ID or AWS_SECRET_ACCESS_KEY not set.'
+ exit 1
AWS_ACCESS_KEY_ID or AWS_SECRET_ACCESS_KEY not set.
```

**Comment by MQasimSarfraz** [comment]
Which version are you using ? In the lastest version `1.4.0` you can use `AWS_USE_EC2_ROLE_FOR_AUTH=true` in place of AWS secrets. https://github.com/Lotto24/aws-ecr-http-proxy/blob/master/files/startup.sh#L26

Can you please give it a try and see if it helps you?

**Comment by 1ricardo** [comment]
Hi @MQasimSarfraz sorry for the late answer, I was very busy with other projects. 

I believe the latest, that is part of config from POD
```
      containers:
        - name: docker-registry-proxy
          image: esailors/aws-ecr-http-proxy:latest
```
but anyway you helped me to resolve that problem, I had to miss those options. 

Thank you very much

**Comment by MQasimSarfraz** [comment]
:+1:  glad to help!
